<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();
if(!$categories->count()){
    return;
}
?>

<h3><?php echo __('Categories'); ?></h3>
<ul class="o-list">

    <?php
    // Loop through categories
    foreach ( $categories as $category ) :
        ?>
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
            <a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="<?php echo($block->isActive($category) ? ' active' : ''); ?>">
                <?php echo $category->getName(); ?>
            </a>
            <?php echo $block->getChildCategoryView($category); ?>
        </li>
    <?php endforeach; ?>
</ul>
